server:
  port: 8081

spring:
  application:
    name: course-service
  profiles:
    active: native
  config:
    import: optional:configserver:http://localhost:8071

#Enable all Spring Boot Actuator endpoints.
management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/


##########TODO: Move this to a file
#example.property= I AM DEFAULT
#spring.datasource.url = jdbc:postgresql://localhost:5432/course_local
#spring.datasource.username = root
#spring.datasource.password = root