server:
  port: 8070

spring:
  application:
    name: eureka-server
  config:
    import: optional:configserver:http://localhost:8071

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    #Change this in order to add a replica of eureka server
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#  #study implications : https://www.baeldung.com/eureka-self-preservation-renewal
#  renewalPercentThreshold: 0.85
  server:
    waitTimeInMsWhenSyncEmpty: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"