server:
  port: 8071

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

#Enable all Spring Boot Actuator endpoints.
management:
  endpoints:
    web:
      exposure:
        include: "*"


#eureka.instance.hostname: localhost
#eureka.client.registerWithEureka: false
#eureka.client.fetchRegistry: false
#eureka.client.serviceUrl.defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#eureka.server.waitTimeInMsWhenSyncEmpty: 5